services:
  frontend:
    build:
      context: ./FinancialManagement
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      BACKEND_URL: ${BACKEND_URL}
